django_doc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('docapps.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docapps/urls.py
from django.urls import path
from . import views

app_name = 'docapps'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('expiring_soon_detail_page/', 
            views.expiring_soon_detail_page, 
            name='expiring_soon_detail_page'),
    path('expired/', views.expired, name='expired'),

    path('email_settings/', views.email_settings, name='email_settings'),
    path('send_email/', views.send_email, name='send_email'),

    path('create_user/', views.create_user, name='create_user'),
    path('user_info/', views.user_info, name='user_info'),
    path('edit_user/<int:pk>/', views.edit_user, name='edit_user'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),


    




]

docapps/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import CharField

# Create your models here.
class Document(models.Model):
    doc_title = models.CharField(max_length=100)
    doc_file = models.FileField()
    email = models.EmailField()
    phone = models.CharField(max_length=11, blank=True)
    expiring_date = models.DateField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    is_expired = models.BooleanField(default=False)
    is_expiring_soon = models.BooleanField(default=False)
    

    class Meta:
        ordering = ['-created']

    def __str__(self):
        if self.expiring_date != None:
            created = self.created.strftime('%d-%m-%Y')
            expired = self.expiring_date.strftime('%d-%m-%Y')
        created = self.created
        expired = self.expiring_date
        return f'{self.doc_title}-created at {created} - expired at {expired}'

class Email(models.Model):
    email_host = models.CharField(max_length=50)
    email_port = models.CharField(max_length=3)
    email_host_user = models.CharField(max_length=50)
    email_host_password = models.CharField(max_length=100)
    email_use_tls = models.BooleanField(default=False)
    email_default_name = models.CharField(max_length=50)   

class Test(models.Model):
    name = models.CharField(max_length=20)

docapps/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . models import Document, Email

class ModelDocumentForm(ModelForm):
    class Meta:
        model = Document
        fields = ['doc_title', 'doc_file', 'expiring_date', 'email', 'phone']

class ModelEmailForm(ModelForm):
    class Meta:
        model = Email
        fields = ['email_host', 'email_port', 'email_host_user', 'email_host_password', 'email_use_tls', 'email_default_name']

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_staff', 'is_active', 'is_superuser', 'date_joined', 'last_login' ]

docapps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User

from django.core.mail import EmailMessage
from django.contrib import messages

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required

from . forms import ModelDocumentForm, CreateUserForm, EditUserForm
from . models import Document


# Create your views here.
@login_required(redirect_field_name='docapps:login')
def dashboard(request):
    docs = Document.objects.all()
    context = {'docs': docs,}
    if request.method == 'POST':
        print(request.POST)
        form = ModelDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = ModelDocumentForm()
            return redirect('docapps:dashboard')
        else:
            print(form.errors)

    return render(request, 'docapps/dashboard.html', context)

@login_required(redirect_field_name='docapps:login')
def expiring_soon_detail_page(request):
    docs = Document.objects.filter(is_expiring_soon=True)
    return render(request, 'docapps/expiring_soon_detail_page.html', {'docs': docs})

@login_required(redirect_field_name='docapps:login')
def expired(request):
    docs = Document.objects.filter(is_expired=True)
    return render(request, 'docapps/expired.html', {'docs': docs})

@login_required(redirect_field_name='docapps:login')
def email_settings(request):
    if request.method == 'POST':
        email.email_host = request.POST['email_host']
        email.email_port =request.POST['email_port']
        email.email_host_user = request.POST['email_host_user']
        email.email_host_password = request.POST['email_host_password']
        email.email_use_tls = request.POST['email_use_tls']
        email.email_default_name = request.POST['email_default_name']
        email.save()
        messages.success(request, f'User has been successfully updated')
        return render(request, 'docapps/email_settings.html')

    return render(request, 'docapps/email_settings.html')

from django.core.mail import send_mail
def send_email(request):
    send_mail('Title', 'Body',
    'shafayetbs@gmail.com',
    ['haydarbsss@gmail.com'],
    fail_silently=False,
    )
    return HttpResponse('Email sent!')

@login_required(redirect_field_name='docapps:login')
@user_passes_test(lambda u: u.is_superuser)
def create_user(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Accounts has been successfully created for {username} ')
            return render(request, 'docapps/createForm.html')
    return render(request, 'docapps/createForm.html')

@login_required(redirect_field_name='docapps:login')
def user_info(request):
    users = User.objects.all()
    return render(request, 'docapps/userList.html', {'users': users})

@login_required(redirect_field_name='docapps:login')
@user_passes_test(lambda u: u.is_superuser)
def edit_user(request, pk):
    user = User.objects.get(id=pk)
    form = EditUserForm(instance=user)

    if request.method == 'POST':
        print(request.POST)
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, f'User has been successfully updated')
            return redirect('docapps:user_info')

    return render(request, 'docapps/userPermission.html', {'form': form})

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            print('login success!')
            messages.success(request, f'Hey {username}! You have been logged in.')
            return redirect('docapps:dashboard')
        else:
            return render(request, 'docapps/login.html')
    return render(request, 'docapps/login.html')

def logout(request):
    auth_logout(request)
    messages.success(request, f'Hey! You have been logged out.')
    return redirect('docapps:login')

docapps/templates/docapps/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Django | Docapp</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

  <!-- css by shafayet -->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
{% include 'docapps/navbar.html' %}
    <div class="container">
    {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{ message.tags }} text-center">
              {{ message }}
          </div>
      {% endfor %}
    {% endif %}
    </div>
    <div class="mt-3">
      {% block dashboard %} {% endblock dashboard %}
    </div>









</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print",]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
  });
</script>

<!-- Page specific script -->
<script>
  $(function () {
    bsCustomFileInput.init();
  });
</script>

</body>
</html>

docapps/templates/docapps/createForm.html
{% extends 'docapps/base.html' %}


{% block dashboard %}

<div class="container">
    {% for message in messages %}
        <p id="message">{{message}}</p>
    {% endfor %}
    <div class="" style="width: 567px; margin: 0 auto;" >
        <div class="col">
            <!-- Horizontal Form -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Horizontal Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="card-body">
                      <div class="form-group">
                        <label for="id_username">Username:</label>  
                        <input type="text" class="form-control" name="username" maxlength="150" autofocus required id="id_username">
                        <span class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                      </div>
                      <!-- Email input -->
                      <div class="form-group">
                        <label for="id_email">Email address:</label>
                        <input type="email" class="form-control" name="email" maxlength="254" id="id_email">
                      </div>
                      <!-- Date -->
                      <div class="form-group">
                        <label for="id_password1">Password:</label> 
                        <input type="password" class="form-control" name="password1" autocomplete="new-password" required id="id_password1">
                        <span class="form-text text-muted"><ul><li>Password can’t be too similar to your other personal information.</li><li>Password must contain at least 8 characters.</li><li>Your password can’t be entirely numeric.</li></ul></span>
                      </div>
                      <!-- Email -->
                      <div class="form-group">
                        <label for="id_password2">Password confirmation:</label>
                        <input type="password" class="form-control" name="password2" autocomplete="new-password" required id="id_password2">
                         <span class="helptext">Enter the same password as before, for verification.</span>
                      </div>
                    </div>
                    <!-- /.card-body -->
        
                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>
{% endblock %}

docapps/templates/docapps/dashboard.html
{% extends 'docapps/base.html' %}
{% block dashboard %}

  <!-- Table and Form -->
  <div class="container-fluid">
    <div class="row p-2">
      <div class="col-sm-8">
        <!-- /.card -->
        <div class="card">
          <div class="card-header">
              <h3 class="card-title">DataTable with default features</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="example1" class="table table-bordered">
              <thead>
              <tr>
                  <th>S/L</th>
                  <th>Doc Title</th>
                  <th>Document</th>
                  <th>Notfn Email</th>
                  <th>Notfn Phone No</th>
                  <th>Doc Created</th>
                  <th>Doc Expired</th>
              </tr>
              </thead>
              <tbody>
              {% if docs is False %}
              <tr class="text-center font-weight-bold color-warning">No data is available</tr>
              {% else %}
                {% for doc in docs %}
                  {% if doc.is_expired %}
                    <tr class="bg-danger">
                      <td> {{ forloop.counter }} </td>
                      <td> {{ doc.doc_title }} </td>
                      <td> {{ doc.doc_file|truncatechars:10 }} </td>
                      <td> {{ doc.email }} </td>
                      <td> {{ doc.phone }} </td>
                      <td> {{ doc.created|date:"d-m-Y" }} </td>
                      <td> {{ doc.expiring_date|date:"d-m-Y" }} </td>
                  </tr>
                  {% elif doc.is_expiring_soon%}
                    <tr class="bg-warning">
                      <td> {{ forloop.counter }} </td>
                      <td> {{ doc.doc_title }} </td>
                      <td> {{ doc.doc_file|truncatechars:10 }} </td>
                      <td> {{ doc.email }} </td>
                      <td> {{ doc.phone }} </td>
                      <td> {{ doc.created|date:"d-m-Y" }} </td>
                      <td> {{ doc.expiring_date|date:"d-m-Y" }} </td>
                    </tr>
                  {% else %}
                  <tr>
                    <td> {{ forloop.counter }} </td>
                    <td> {{ doc.doc_title }} </td>
                    <td> {{ doc.doc_file|truncatechars:10 }} </td>
                    <td> {{ doc.email }} </td>
                    <td> {{ doc.phone }} </td>
                    <td> {{ doc.created|date:"d-m-Y" }} </td>
                    <td> {{ doc.expiring_date|date:"d-m-Y" }} </td>
                  </tr>
                  {% endif %}
                {% endfor %}
              {% endif %}
              </tbody>
              <tfoot>
              <tr>
                <th>S/L</th>
                <th>Doc Title</th>
                <th>Document</th>
                <th>Notfn Email</th>
                <th>Notfn Phone No</th>
                <th>Doc Created</th>
                <th>Doc Expired</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    <div class="col-sm-4">
      <!--Form Card -->
      <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Upload New Document</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-body">
              <div class="form-group">
                <label for=doc_title>Document Title:</label>
                <input type="text" class="form-control" id="doc_title" name="doc_title" placeholder="Enter to name the file " required>
              </div>
              <!-- File input -->
              <div class="form-group">
                <label for="id_doc_file">File input:</label>
                <input type="file" class="form-control" id="id_doc_file" name="doc_file" style="line-height: 18px;" required>
              </div>
              <!-- Date -->
              <div class="form-group">
                <label for=id_expiring_date>Expiring Date:</label>
                <input type="date" class="form-control" id="id_expiring_date" name="expiring_date" placeholder="dd-mm-yyyy" required>
              </div>
              <!-- Email -->
              <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email to get notification">
              </div>
              <!-- phone mask -->
              <div class="form-group">
                <label>BD Phone Number:</label>

                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                  </div>
                  <input type="text" class="form-control"  id="phone" name="phone" data-inputmask='"mask": "99999-999999"' data-mask placeholder="+880 1813******">
                </div>
                <!-- /.input group -->
              </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
      </div>
      <!-- /.Form card -->
    </div>
    </div>
  </div>
  <!-- /.Table and Form -->
{% endblock %}

docapps/templates/docapps/email_settings.html
{% extends 'docapps/base.html' %}
{% block dashboard %}

<div class="container mt-5">
  <div class="card card-primary">
    <div class="card-header text-center">
        <h3 class="card-title">E-mail Settings</h3>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="card-body">
        <div class="row">
          <div class="col">
            <div class="form-group">
              <label for="id_email_host">Email Host *</label>
              <input type="text" class="form-control" id="id_email_host" name="email_host" placeholder="(e.g., smtp.domain.com)" required>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label for=id_email_port>EMAIL_PORT *</label>
              <input type="number" class="form-control" id="id_email_port" name="email_port" placeholder="(e.g., 587)" required>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col">
            <div class="form-group">
              <label for=id_host_user>Email Host User *</label>
              <input type="email" class="form-control" id="id_host_user" name="host_user" placeholder="Enter your email  from which your email will be sent to " required>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label for=id_host_password>Email Host Password *</label>
              <input type="password" class="form-control" id="id_host_password" name="host_password" placeholder="Enter email host password " required>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <div class="form-group">
              <label for=id_sender_name>Email Sender Name </label>
              <input type="text" class="form-control" id="id_sender_name" name="sender_name" placeholder="You can type your company name here ">
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label for=id_use_tls>Email Use TLS *</label>
              <input type="text" class="form-control" id="id_use_tls" name="use_tls" placeholder="Type 'True or False' " required>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer">
      <button type="submit" class="btn btn-primary float-right">Submit</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

docapps/templates/docapps/expired.html
{% extends 'docapps/base.html' %}

{% block dashboard %}
<div class="container mt-2">
    <div class="card card-primary" style="margin: 0 auto;>
        <div class="row">
            <!-- /.card -->
            <div class="card-header">
                <h3 class="card-title">All Documents are Expiring Soon</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered">
                <thead>
                <tr>
                    <th>S/L</th>
                    <th>Doc Title</th>
                    <th>Document</th>
                    <th>Notfn Email</th>
                    <th>Notfn Phone No</th>
                    <th>Doc Created</th>
                    <th>Doc Expired</th>
                </tr>
                </thead>
                <tbody>
                {% if docs is False %}
                <tr class="text-center font-weight-bold color-warning">No data is available</tr>
                {% else %}
                    {% for doc in docs %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ doc.doc_title }} </td>
                        <td> {{ doc.doc_file|truncatechars:10 }} </td>
                        <td> {{ doc.email }} </td>
                        <td> {{ doc.phone }} </td>
                        <td> {{ doc.created|date:"d-m-Y" }} </td>
                        <td> {{ doc.expiring_date|date:"d-m-Y" }} </td>
                    </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
                <tfoot>
                <tr>
                    <th>S/L</th>
                    <th>Doc Title</th>
                    <th>Document</th>
                    <th>Notfn Email</th>
                    <th>Notfn Phone No</th>
                    <th>Doc Created</th>
                    <th>Doc Expired</th>
                </tr>
                </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
    </div>
</div>

{% endblock %}

docapps/templates/docapps/navbar.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand" style="background-color: #20c997;">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item d-none d-sm-inline-block mr-2">
        <a href="{% url 'docapps:dashboard' %}" class="navbar-brand">SYNCHIT</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    {% if request.user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <!-- Full Screen -->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <!-- Admin Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" "font-weight-bold" data-toggle="dropdown" href="#">
          <i class="far fa-user mr-1"></i>Admin
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-center">
          <a href="{% url 'docapps:dashboard' %}" class="dropdown-item">
            <i class="fas fa-user "></i> Dashboard
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'docapps:user_info' %}" class="dropdown-item">
            <i class="fas fa-wrench"></i> User
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'docapps:create_user' %}" class="dropdown-item">
            <i class="fas fa-plus-circle"></i> Create User
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'docapps:email_settings' %}" class="dropdown-item">
            <i class="fas fa-envelope"></i> Mail Settings
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-paper-plane"></i> SMS Stettings
          </a>
        </div>
      </li>

      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">{{ all_notifications }}</span>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-center">
          <a href="{% url 'docapps:expired' %}" class="dropdown-item">
            <i class="fas fa-times text-danger"></i> {{ expired_notification }} Documents Expired
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'docapps:expiring_soon_detail_page' %}" class="dropdown-item">
            {% if expiring_soon_notification %}
            <i class="fas fa-exclamation-triangle text-warning"></i> {{ expiring_soon_notification }} Documents Expiring Soon
            {% else %}
            <i class="fas fa-check-circle text-success"></i> No Documents to be expired soon
            {% endif %}
          </a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" "font-weight-bold" href="{% url 'docapps:logout' %}">
          <i class="fas fa-sign-out-alt"></i>Log out
        </a>
      </li>
    </ul>
    {% endif %}
  </nav>
  <!-- /.navbar -->

docapps/templates/docapps/userList.html
{% extends 'docapps/base.html' %}

{% block dashboard %}  
<div class="container">
    <!-- /.row -->
    <div class="row">
        <div class="col-12">
            <div class="card">
            <div class="card-header">
                <h3 class="card-title">Select user to change</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                <thead>
                    <tr>
                    <th>#</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Staff</th>
                    <th>Superuser</th>
                    <th>Last Login</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td> {{ user.id }} </td>
                        <td><a href=" {% url 'docapps:edit_user' user.id %} ">{{ user.username }}</a></td>
                        <td> {{ user.email }} </td>
                        <td> {{ user.first_name }} </td>
                        <td> {{ user.last_name }} </td>
                        <td> {{ user.is_staff }} </td>
                        <td> {{ user.is_superuser }} </td>
                        <td> {{ user.last_login}} </td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
    <!-- /.row -->
</div>  
{% endblock %}